app = 'recast'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  count = 1

[env]
  SHARD_COUNT = "1"
  SHARD_ID = "0"
